### ISSUE TITLE
Final JSON record has extraneous comma

### ISSUE THREAD

**Issue by pjotrp** [vcflib/bio-vcf#33]
This is a long-standing bug. bio-vcf now knows about the final record and it can be fixed - we should add an example.

**Comment by brainstorm** [comment]
Oh, noes, I was just about to use that magic VCF to JSON functionality to export (hopefully) into a Pandas dataframe to be used by scikit-learn :) ... If you tell me how to run it, I could look after that bug.

**Comment by pjotrp** [comment]
The easy fix now is to pipe into sed or grep to edit the final output of the VCF file. When I have time I'll put in a real fix.
