### ISSUE TITLE
Debian package for bio-vcf

### ISSUE THREAD

**Issue by pjotrp** [vcflib/bio-vcf#49]
bio-vcf installs as a Ruby gem and runs as a binary. It will be published as a sibling to libvcf. It would be good to a have a Debian package. @mr-c do you mind initiating the process?

**Comment by mr-c** [comment]
@pjotrp We're in a freeze right now, so no new packages will be accepted for a bit. You can file a "request for packaging" via email by following https://www.debian.org/devel/wnpp/#l2 (or [via](https://www.debian.org/devel/wnpp/#l1) `reportbug --email username@domain.tld wnpp` if you have access to a Debian system/container)

**Comment by pjotrp** [comment]
Submitted wnpp
