### ISSUE TITLE
how to convert vcf to tab-sep file?

### ISSUE THREAD

**Issue by xiucz** [vcflib/bio-vcf#50]
Hi, 

After reading the README, I still could not find a way to convert vcf to tab-sep file? Including all information in `INFO` and `FORMAT ` feild.

Thank you a lot.
xiucz.

**Comment by abalter** [comment]
Use `vcf2tsv` from the [vcflib](https://github.com/vcflib/vcflib) library.

**Comment by pjotrp** [comment]
> Use `vcf2tsv` from the [vcflib](https://github.com/vcflib/vcflib) library.

Yes. bio-vcf you can split the sub fields with a lambda - if you want a subset of data that can be useful.
